# Generated by Django 3.1.4 on 2021-01-02 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_fotografi', models.ImageField(blank=True, null=True, upload_to='profiles/kullanici_profil_fotograflari')),
                ('toplam_harcanan_para', models.DecimalField(decimal_places=2, default=0, max_digits=999)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Magaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('profil_fotografi', models.ImageField(blank=True, null=True, upload_to='profiles/magaza_profil_fotograflari')),
                ('tanitim', models.TextField()),
                ('brut_kazanc', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
                ('ortalama_puan', models.DecimalField(decimal_places=1, max_digits=2)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=150)),
                ('aciklama', models.TextField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=999)),
                ('kargo_ucreti', models.DecimalField(decimal_places=2, max_digits=3)),
                ('puan', models.DecimalField(decimal_places=1, max_digits=2)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.kategori')),
                ('satici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.magaza')),
                ('satin_alanlar', models.ManyToManyField(to='profiles.Kullanici')),
            ],
        ),
        migrations.AddField(
            model_name='magaza',
            name='urunler',
            field=models.ManyToManyField(to='profiles.Urun'),
        ),
    ]
