# Generated by Django 3.1.4 on 2021-01-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='sepet',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Urun'),
        ),
        migrations.AlterField(
            model_name='magaza',
            name='ortalama_puan',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='magaza',
            name='urunler',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Urun'),
        ),
    ]
