# Generated by Django 3.1.4 on 2021-01-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210102_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='puan',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='urun',
            name='satin_alanlar',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Kullanici'),
        ),
    ]
