# Generated by Django 3.1.4 on 2021-01-02 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210102_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('baslik', models.CharField(max_length=50)),
                ('icerik', models.TextField()),
                ('puan', models.DecimalField(decimal_places=1, max_digits=2)),
                ('yorum_yapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.kullanici')),
                ('yorum_yapilan_urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.urun')),
            ],
        ),
    ]
