# Generated by Django 3.1.4 on 2021-01-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210106_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magaza',
            name='kargolandi_bildirimi',
            field=models.TextField(default='kargolandı', verbose_name='Ürün kargolandı bildirimi'),
            preserve_default=False,
        ),
    ]
