# Generated by Django 3.1.4 on 2021-01-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210106_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magaza',
            name='kargolandi_bildirimi',
        ),
    ]
