# Generated by Django 3.1.4 on 2021-01-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_magaza_kargolandi_bildirimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='kime_kargolandi',
            field=models.ManyToManyField(blank=True, related_name='kime_kargolandi', to='profiles.Kullanici', verbose_name='Şu kişilere kargolandı.'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='sepet',
            field=models.ManyToManyField(blank=True, to='profiles.Urun', verbose_name='Sepet'),
        ),
        migrations.AlterField(
            model_name='magaza',
            name='urunler',
            field=models.ManyToManyField(blank=True, to='profiles.Urun', verbose_name='Ürünler'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='satin_alanlar',
            field=models.ManyToManyField(blank=True, related_name='satin_alanlar', to='profiles.Kullanici', verbose_name='Bu ürünü satın alanlar'),
        ),
    ]
