# Generated by Django 3.1.4 on 2021-01-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210106_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='teslim_alinanlar',
            field=models.ManyToManyField(blank=True, related_name='teslim_alinanlar', to='profiles.Urun', verbose_name='Satın alınan ürünler'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='sepet',
            field=models.ManyToManyField(blank=True, related_name='sepet', to='profiles.Urun', verbose_name='Sepet'),
        ),
    ]
