# Generated by Django 3.1.4 on 2021-01-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210106_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='kargo_ucreti',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Kargo ücreti'),
        ),
    ]
