# Generated by Django 3.1.4 on 2021-01-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_magaza_sifre'),
    ]

    operations = [
        migrations.AddField(
            model_name='magaza',
            name='e_mail',
            field=models.EmailField(default='default@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magaza',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='magaza',
            name='password',
            field=models.CharField(default='sifre', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='magaza',
            name='ad',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ad'),
        ),
    ]
