# Generated by Django 3.1.4 on 2021-01-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20210108_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magaza',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='magaza',
            name='password',
        ),
    ]
