# Generated by Django 3.1.4 on 2021-01-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20210109_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magaza',
            old_name='ad',
            new_name='giris_adi',
        ),
        migrations.AddField(
            model_name='magaza',
            name='gorunen_ad',
            field=models.CharField(default='Yeni Ticaret', max_length=100, unique=True, verbose_name='Mağazanın adı'),
            preserve_default=False,
        ),
    ]
