# Generated by Django 3.1.4 on 2021-01-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20210109_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='slug',
            field=models.CharField(default='slugdeneme', max_length=150, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
