# Generated by Django 3.1.4 on 2021-01-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_urun_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magaza',
            name='urunler',
        ),
        migrations.AlterField(
            model_name='urun',
            name='slug',
            field=models.CharField(blank=True, max_length=150, verbose_name='Slug'),
        ),
    ]
