# Generated by Django 3.1.4 on 2021-01-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_kategori_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='slug',
            field=models.CharField(blank=True, max_length=150, verbose_name='Slug'),
        ),
    ]
