# Generated by Django 3.1.3 on 2021-01-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_magaza_bekleyen_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='satin_alinanlar',
            field=models.ManyToManyField(blank=True, related_name='satin_alinanlar', to='profiles.Urun', verbose_name='Sipariş edilen ürünler'),
        ),
    ]
