# Generated by Django 3.1.4 on 2021-02-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20210130_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='satin_alinanlar',
            field=models.ManyToManyField(blank=True, related_name='satin_alinanlar', to='profiles.Urun', verbose_name='Satın alınan ürünler'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='siparisler',
            field=models.ManyToManyField(blank=True, to='profiles.Siparis', verbose_name='Siparişler'),
        ),
        migrations.AlterField(
            model_name='magaza',
            name='siparisler',
            field=models.ManyToManyField(blank=True, to='profiles.Siparis', verbose_name='Siparişler'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='kargoya_verilme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kargoya verilme tarihi'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='teslim_alinma_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Teslim alınma tarihi'),
        ),
    ]
