# Generated by Django 3.1.4 on 2021-02-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20210201_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='adres',
            field=models.CharField(default='bla bla sokagi', max_length=150, verbose_name='Adres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siparis',
            name='kart_guvenlik_kodu',
            field=models.CharField(default=133, max_length=3, verbose_name='CVV/CVC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siparis',
            name='kart_skt',
            field=models.CharField(default=0.44, max_length=5, verbose_name='Kart SKT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siparis',
            name='satin_alan_ad',
            field=models.CharField(default='mehmet', max_length=100, verbose_name='Satın alan adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siparis',
            name='satin_alan_soyad',
            field=models.CharField(default='yilmaz', max_length=100, verbose_name='Satın alan soyadı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siparis',
            name='tel_no',
            field=models.CharField(default=905547856231, max_length=13, verbose_name='Telefon numarası'),
            preserve_default=False,
        ),
    ]
