# Generated by Django 3.1.4 on 2021-02-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20210212_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magaza',
            name='bekleyen_para',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999, verbose_name='Askıdaki para'),
        ),
        migrations.AlterField(
            model_name='magaza',
            name='brut_kazanc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999, verbose_name='Brüt kazanç (Site komisyonu hariç)'),
        ),
        migrations.AlterField(
            model_name='magaza',
            name='net_kazanc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999, verbose_name='Net kazanç'),
        ),
    ]
