# Generated by Django 3.1.4 on 2021-02-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20210212_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanici',
            name='siparisler',
        ),
    ]
