# Generated by Django 3.1.4 on 2021-02-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_remove_kullanici_siparisler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magaza',
            name='siparisler',
        ),
    ]
