# Generated by Django 3.1.4 on 2021-02-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_remove_magaza_siparisler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='teslim_alinanlar',
            field=models.ManyToManyField(blank=True, related_name='teslim_alinanlar', to='profiles.Siparis', verbose_name='Tamamlanan siparişler'),
        ),
    ]
