# Generated by Django 3.1.4 on 2021-02-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_remove_kullanici_teslim_alinanlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='magaza',
            name='slug',
            field=models.CharField(blank=True, max_length=100, verbose_name='Slug'),
        ),
    ]
